<a href="https://colab.research.google.com/github/rokzeezee/Machine-Learning-/blob/main/Spam_Detecting_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn .pipeline import make_pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [107]:
data = pd.read_csv("/content/spam.csv")

data

#data.describe().T

data.groupby("Category").describe()


Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [3]:
data["spam"]=data["Category"].apply(lambda x : 1 if x == "spam" else 0)
data

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [4]:
X = data.iloc[:,1]
y= data.iloc[:,2]

In [37]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [38]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

In [90]:
 X_train , X_test ,y_train ,y_test =train_test_split(X,y, test_size = 0.2, random_state=1)

In [91]:
X_train.shape , X_test.shape ,y_train.shape ,y_test.shape 

((4457,), (1115,), (4457,), (1115,))

In [92]:
#find word count amd store data as matrix (as when scaling standardscaler)

cv = CountVectorizer()

#X_train_count = cv.fit_transform(X_train)

X_train = cv.fit_transform(X_train)

X_test = cv.transform(X_test)


In [93]:
X_train

<4457x7711 sparse matrix of type '<class 'numpy.int64'>'
	with 58978 stored elements in Compressed Sparse Row format>

In [94]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [95]:
NB_model= MultinomialNB()
NB_model.fit(X_train,y_train) 



MultinomialNB()

In [97]:
Pred = NB_model.predict(X_test)

In [98]:
score = NB_model.score(X_test , y_test)
score

0.989237668161435

In [101]:
#PRE-TEST HAM

email_ham = ["hey wanna ,eat up for the game ?"]

email_ham_count = cv.transform(email_ham)

NB_model.predict(email_ham_count)

array([0])

In [102]:

email_spam = [" payment of $50,000 "]

email_spam_count = cv.transform(email_spam )

NB_model.predict(email_spam_count)

array([1])